/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageResult extends javax.swing.JFrame {
     String Username="root";
        String password=null;
        String url="jdbc:mysql://127.0.0.1/school";
        Connection connection = null;
        PreparedStatement pre;

    /**
     * Creates new form AddResult
     */
    public ManageResult() {
        initComponents();
        this.setLocationRelativeTo(null);
        showtabledata(ShowTable,"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Studen_ID = new javax.swing.JTextField();
        Cour_ID = new javax.swing.JTextField();
        Descript = new javax.swing.JTextField();
        MArkK = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ShowTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Manage Result");

        jLabel3.setText("Course ID");

        jLabel4.setText("Result");

        jLabel5.setText("Description");

        Descript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptActionPerformed(evt);
            }
        });

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Course ID", "Result", "Description"
            }
        ));
        ShowTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ShowTable);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Studen_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cour_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MArkK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Descript, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Studen_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cour_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MArkK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Descript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
               String Studen_IDs=String.valueOf(Studen_ID.getText());//Studen_ID,Cour_ID,MArkK,Descript
          String Cour_IDs=String.valueOf(Cour_ID.getText());
          String MArkKs=String.valueOf(MArkK.getText());
          String Descripts=String.valueOf(Descript.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        }
          try{
            connection = (Connection) DriverManager.getConnection(url, Username, password);
            //JOptionPane.showMessageDialog(null,"Connect Database  ");
            Update(Studen_IDs,Cour_IDs,MArkKs,Descripts);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ShowTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTableMouseClicked
        // TODO add your handling code here:
        
         int rowindex=ShowTable.getSelectedRow();//
        DefaultTableModel model=(DefaultTableModel) ShowTable.getModel();
        Studen_ID.setText(model.getValueAt(rowindex, 0).toString());
        Cour_ID.setText(model.getValueAt(rowindex, 1).toString());
        MArkK.setText(model.getValueAt(rowindex, 2).toString());
        Descript.setText(model.getValueAt(rowindex, 3).toString());
    }//GEN-LAST:event_ShowTableMouseClicked

    private void DescriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: remove
        String studID=String.valueOf(Studen_ID.getText());
         try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        }
          try{
            connection = (Connection) DriverManager.getConnection(url, Username, password);
            //JOptionPane.showMessageDialog(null,"Connect Database  ");
            Delete(studID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdminPanale adminPanale = new AdminPanale();
        adminPanale.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageResult().setVisible(true);
            }
        });
    }
    
     public void Delete(String studID) { 
                try{
                    connection = (Connection) DriverManager.getConnection(url, Username, password);
                // String sql = "INSERT INTO register(name,username,phone,Password,Gender) VALUES(Fname,Usename,phon,pass,gender)";
                    String sql = "DELETE FROM  result WHERE Stu_ID = ?";
                     	 	 	 	 	 	 
                   pre = connection.prepareStatement(sql);  		                   
                  //Studentid,fistname,lastname,Gender,datet,phone,addres 
                  pre.setString(1, studID);
                  
                 
                
                  if(pre.executeUpdate()>0){
                      JOptionPane.showMessageDialog(null," Delete Successfully.");
                      showtabledata(jTable1,"0");
                  }else{
                      JOptionPane.showMessageDialog(null,"Delete not Successfully.");
                  }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Exception is"+e);
                }
            
            
    }
    public void Update(String Studen_IDs,String Cour_IDs,String MArkKs,String Descripts){
                try{
                    connection = (Connection) DriverManager.getConnection(url, Username, password);
                // String sql = "INSERT INTO register(name,username,phone,Password,Gender) VALUES(Fname,Usename,phon,pass,gender)";
                    String sql = "UPDATE result SET Course_ID = ?,Mark = ?, Description = ? WHERE Stu_ID  = ?"; 
                     	 	 	 	 	 	 
                   pre = connection.prepareStatement(sql);  		                   
                  //Studentid,fistname,lastname,Gender,datet,phone,addres 
                  pre.setString(4, Studen_IDs);
                  pre.setString(1, Cour_IDs);
                  pre.setString(2, MArkKs);
                  pre.setString(3, Descripts);
                   
                 
                
                  if(pre.executeUpdate()>0){
                      JOptionPane.showMessageDialog(null,"Information Update  The Database Successfully.");
                  }else{
                      JOptionPane.showMessageDialog(null,"Information Not Update The Database Successfully.");
                  }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Exception is"+e);
                }
            
            
    }
    public void showtabledata(JTable table, String values){
        
        
          try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        }
          try{
              
            connection = (Connection) DriverManager.getConnection(url, Username, password);
           // JOptionPane.showMessageDialog(null,"Connect Database  ");
            //insert(Fullname,Usernames,Phone,Password,cPassword,Gender);
            String sql="SELECT * FROM result WHERE Course_ID LIKE ?";//Course_ID 	Mark 	Description 
            pre = connection.prepareStatement(sql);
            pre.setString(1, "%"+values+"%");
            ResultSet result=pre.executeQuery();
            DefaultTableModel model=(DefaultTableModel) table.getModel();
            Object[] row;
            while(result.next()){
                row=new Object[5];
                row[0]=result.getInt(2);
                row[1]=result.getInt(3);
                row[2]=result.getDouble(4);
                row[3]=result.getString(5);
                
               
                
                model.addRow(row);
                //JOptionPane.showMessageDialog(null,"Succesfullt Table Data Show.");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Exception "+e);
        } 
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cour_ID;
    private javax.swing.JTextField Descript;
    private javax.swing.JTextField MArkK;
    private javax.swing.JTable ShowTable;
    private javax.swing.JTextField Studen_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
